import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src     = Split("""
communication.c
uppercomputer.c
com_dev/com_can.c
com_dev/com_uart.c
""")

CPPPATH += [cwd + '/com_dev']

group = DefineGroup('HEROLib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
